### ISSUE TITLE
It does not show in Chocolat 3.1.4

### ISSUE THREAD

**Issue by sebastianf** [mikegabriel/marked.chocmixin#2]
I have not menu entry in Go.
It worked in an older version.

**Comment by eliasmaier** [comment]
Thank you for reporting the issue.
As I don't have a V3 license and don't use Chocolat anymore, this mixxin is no longer actively developed.
Feel free to fork and fix it yourself.

**Comment by sebastianf** [comment]
Ok thanks this should be a chocolat issue
